Nov  3 09:25:47 scs-rpi-011 python3[756]: 09:25:47.790:         mqtt: received: {"south-coast-science-production/reference/loc/531/particulates": {"rec": "2023-11-03T09:25:45Z", "tag": "scs-bgx-531", "ver": 2.0, "src": "N3", "val": {"per": 4.1, "pm1": 1.3, "pm2p5": 5.4, "pm10": 7.6, "bin": [53, 26, 20, 2, 7, 7, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "mtf1": 26, "mtf3": 34, "mtf5": 33, "mtf7": 0, "sfr": 3.68, "sht": {"hmd": 43.2, "tmp": 20.3}}, "exg": {"src": "rn20", "val": {"pm1": 1.6, "pm2p5": 2.7, "pm10": 5.4}}}}
Nov  3 09:25:49 scs-rpi-011 sh[757]: get: query: /api/api
Nov  3 09:25:49 scs-rpi-011 sh[757]: get: query: /api/api
Nov  3 09:25:49 scs-rpi-011 sh[757]: get: query: /api/api
Nov  3 09:25:49 scs-rpi-011 sh[757]: get: query: /api/JuA71dSBcObSJi255VatGFEQxOFDu6lOzDqCtjtI/lights
Nov  3 09:25:49 scs-rpi-011 sh[757]: get: query: /api/cdC-BMk6NZU18JFvgJKjrJGan51SzPmGwu1T6sEx/lights
Nov  3 09:25:49 scs-rpi-011 sh[757]: get: query: /api/o2uPtmG6TMX3Z--VACzUl1YMP7vJmtxEDf3uEZIJ/lights
Nov  3 09:25:49 scs-rpi-011 sh[757]: Traceback (most recent call last):
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_core/src/scs_core/client/http_client.py", line 128, in __request
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self.__conn.request(method, url, body=body, headers=headers)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 1260, in request
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self._send_request(method, url, body, headers, encode_chunked)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 1306, in _send_request
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self.endheaders(body, encode_chunked=encode_chunked)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 1255, in endheaders
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self._send_output(message_body, encode_chunked=encode_chunked)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 1030, in _send_output
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self.send(msg)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 970, in send
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self.connect()
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 942, in connect
Nov  3 09:25:49 scs-rpi-011 sh[757]:     (self.host,self.port), self.timeout, self.source_address)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/socket.py", line 727, in create_connection
Nov  3 09:25:49 scs-rpi-011 sh[757]:     raise err
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
Nov  3 09:25:49 scs-rpi-011 sh[757]:     sock.connect(sa)
Nov  3 09:25:49 scs-rpi-011 sh[757]: OSError: [Errno 113] No route to host
Nov  3 09:25:49 scs-rpi-011 sh[757]: During handling of the above exception, another exception occurred:
Nov  3 09:25:49 scs-rpi-011 sh[757]: Traceback (most recent call last):
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/desk.py", line 162, in <module>
Nov  3 09:25:49 scs-rpi-011 sh[757]:     response = manager.set_state(light.index, state)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/manager/light_manager.py", line 168, in set_state
Nov  3 09:25:49 scs-rpi-011 sh[757]:     jdict = self._rest_client.put(request_path, state.as_json())
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/client/rest_client.py", line 104, in put
Nov  3 09:25:49 scs-rpi-011 sh[757]:     response_jstr = self.__http_client.put(self.__http_path(path), payload_jstr, self.__headers)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_core/src/scs_core/client/http_client.py", line 102, in put
Nov  3 09:25:49 scs-rpi-011 sh[757]:     response = self.__request("PUT", path, payload, headers)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_core/src/scs_core/client/http_client.py", line 134, in __request
Nov  3 09:25:49 scs-rpi-011 sh[757]:     raise ResourceUnavailableException(self.__host + url, ex)
Nov  3 09:25:49 scs-rpi-011 sh[757]: scs_core.client.resource_unavailable_exception.ResourceUnavailableException: ResourceUnavailableException:{url:192.168.1.47/api/JuA71dSBcObSJi255VatGFEQxOFDu6lOzDqCtjtI/lights/1/state, original_exception:[Errno 113] No route to host}
Nov  3 09:25:49 scs-rpi-011 sh[757]: During handling of the above exception, another exception occurred:
Nov  3 09:25:49 scs-rpi-011 sh[757]: Traceback (most recent call last):
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_core/src/scs_core/client/http_client.py", line 128, in __request
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self.__conn.request(method, url, body=body, headers=headers)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 1260, in request
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self._send_request(method, url, body, headers, encode_chunked)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 1306, in _send_request
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self.endheaders(body, encode_chunked=encode_chunked)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 1255, in endheaders
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self._send_output(message_body, encode_chunked=encode_chunked)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 1030, in _send_output
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self.send(msg)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 970, in send
Nov  3 09:25:49 scs-rpi-011 sh[757]:     self.connect()
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/http/client.py", line 942, in connect
Nov  3 09:25:49 scs-rpi-011 sh[757]:     (self.host,self.port), self.timeout, self.source_address)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/socket.py", line 727, in create_connection
Nov  3 09:25:49 scs-rpi-011 sh[757]:     raise err
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
Nov  3 09:25:49 scs-rpi-011 sh[757]:     sock.connect(sa)
Nov  3 09:25:49 scs-rpi-011 sh[757]: OSError: [Errno 113] No route to host
Nov  3 09:25:49 scs-rpi-011 sh[757]: During handling of the above exception, another exception occurred:
Nov  3 09:25:49 scs-rpi-011 sh[757]: Traceback (most recent call last):
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/desk.py", line 187, in <module>
Nov  3 09:25:49 scs-rpi-011 sh[757]:     response = manager.set_state(light.index, LightState.white())
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/manager/light_manager.py", line 168, in set_state
Nov  3 09:25:49 scs-rpi-011 sh[757]:     jdict = self._rest_client.put(request_path, state.as_json())
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/client/rest_client.py", line 104, in put
Nov  3 09:25:49 scs-rpi-011 sh[757]:     response_jstr = self.__http_client.put(self.__http_path(path), payload_jstr, self.__headers)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_core/src/scs_core/client/http_client.py", line 102, in put
Nov  3 09:25:49 scs-rpi-011 sh[757]:     response = self.__request("PUT", path, payload, headers)
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_core/src/scs_core/client/http_client.py", line 134, in __request
Nov  3 09:25:49 scs-rpi-011 sh[757]:     raise ResourceUnavailableException(self.__host + url, ex)
Nov  3 09:25:49 scs-rpi-011 sh[757]: scs_core.client.resource_unavailable_exception.ResourceUnavailableException: ResourceUnavailableException:{url:192.168.1.47/api/JuA71dSBcObSJi255VatGFEQxOFDu6lOzDqCtjtI/lights/1/state, original_exception:[Errno 113] No route to host}
Nov  3 09:25:49 scs-rpi-011 python3[756]: 09:25:49.944:         mqtt: received: {"south-coast-science-production/freshfield-environment/loc/1/gases": {"rec": "2023-11-03T09:25:49Z", "tag": "scs-be2-806", "ver": 1.0, "src": "AFE", "val": {"CO2": {"cnc": 756.5}, "sht": {"hmd": 58.9, "tmp": 21.5}}}}
Nov  3 09:25:49 scs-rpi-011 sh[757]: chroma: assembly-co2: domain value: 756.5
Nov  3 09:25:49 scs-rpi-011 sh[757]: chroma: finishing
Nov  3 09:25:49 scs-rpi-011 sh[757]: Traceback (most recent call last):
Nov  3 09:25:49 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/chroma.py", line 127, in <module>
Nov  3 09:25:49 scs-rpi-011 sh[757]:     sys.stdout.flush()
Nov  3 09:25:49 scs-rpi-011 sh[757]: BrokenPipeError: [Errno 32] Broken pipe
Nov  3 09:25:49 scs-rpi-011 sh[757]: Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
Nov  3 09:25:49 scs-rpi-011 sh[757]: BrokenPipeError: [Errno 32] Broken pipe
Nov  3 09:25:57 scs-rpi-011 python3[756]: 09:25:57.788:         mqtt: received: {"south-coast-science-production/reference/loc/531/particulates": {"rec": "2023-11-03T09:25:55Z", "tag": "scs-bgx-531", "ver": 2.0, "src": "N3", "val": {"per": 4.1, "pm1": 1.3, "pm2p5": 6.7, "pm10": 22.5, "bin": [49, 25, 20, 3, 7, 9, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "mtf1": 28, "mtf3": 32, "mtf5": 35, "mtf7": 0, "sfr": 3.61, "sht": {"hmd": 43.2, "tmp": 20.3}}, "exg": {"src": "rn20", "val": {"pm1": 1.3, "pm2p5": 2.9, "pm10": 5.5}}}}
Nov  3 09:25:57 scs-rpi-011 sh[757]: node: finishing
Nov  3 09:25:57 scs-rpi-011 sh[757]: Traceback (most recent call last):
Nov  3 09:25:57 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/node.py", line 98, in <module>
Nov  3 09:25:57 scs-rpi-011 sh[757]:     sys.stdout.flush()
Nov  3 09:25:57 scs-rpi-011 sh[757]: BrokenPipeError: [Errno 32] Broken pipe
Nov  3 09:25:57 scs-rpi-011 sh[757]: Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
Nov  3 09:25:57 scs-rpi-011 sh[757]: BrokenPipeError: [Errno 32] Broken pipe
Nov  3 09:25:59 scs-rpi-011 sh[757]: uds_receiver: finishing
Nov  3 09:25:59 scs-rpi-011 sh[757]: Traceback (most recent call last):
Nov  3 09:25:59 scs-rpi-011 sh[757]:   File "/home/pi/SCS/scs_philips_hue/src/scs_philips_hue/uds_receiver.py", line 72, in <module>
Nov  3 09:25:59 scs-rpi-011 sh[757]:     sys.stdout.flush()
Nov  3 09:25:59 scs-rpi-011 sh[757]: BrokenPipeError: [Errno 32] Broken pipe
Nov  3 09:25:59 scs-rpi-011 sh[757]: Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
Nov  3 09:25:59 scs-rpi-011 sh[757]: BrokenPipeError: [Errno 32] Broken pipe
Nov  3 09:25:59 scs-rpi-011 python3[756]: 09:25:59.967:         mqtt: received: {"south-coast-science-production/freshfield-environment/loc/1/gases": {"rec": "2023-11-03T09:25:59Z", "tag": "scs-be2-806", "ver": 1.0, "src": "AFE", "val": {"CO2": {"cnc": 756.1}, "sht": {"hmd": 58.9, "tmp": 21.5}}}}
Nov  3 09:26:00 scs-rpi-011 systemd[1]: scs_philips_hue.service: Main process exited, code=exited, status=1/FAILURE
Nov  3 09:26:00 scs-rpi-011 systemd[1]: scs_philips_hue.service: Failed with result 'exit-code'.
Nov  3 09:26:05 scs-rpi-011 systemd[1]: scs_philips_hue.service: Service RestartSec=5s expired, scheduling restart.
Nov  3 09:26:05 scs-rpi-011 systemd[1]: scs_philips_hue.service: Scheduled restart job, restart counter is at 1.
Nov  3 09:26:05 scs-rpi-011 systemd[1]: Stopped SCS Philips Hue Display.
Nov  3 09:26:05 scs-rpi-011 systemd[1]: Started SCS Philips Hue Display.
